### PR TITLE
fix(setup): write configuration files directly from memory

### LINKED ISSUE #782: Embed default config files into `hc` binary, make `hc setup` write them to the config folder
Update the `hc` binary to include strings of the basic config files in `config/`, e.g. Orgs.kdl, Binary.kdl, etc. 

Update `hc setup` command to write these files from the binary to the resolved config folder, thus removing the need to fetch them from the internet.

### PR DESCRIPTION
**Pull request by KirilldogU**
During hc setup write config files from memory, without local dirs or remote source.

Resolves #782

### CODE REVIEW

File: hipcheck/src/setup.rs [hunk 1]
```diff
@@ -1,182 +1,37 @@
...
+use crate::error::Result;
+use std::io::Write;
+use std::{fs::File, path::Path};
+
+static BINARY_TOML: &str = include_str!("../../config/Binary.toml");
+static EXEC_KDL: &str = include_str!("../../config/Exec.kdl");
+static HIPCHECK_KDL: &str = include_str!("../../config/Hipcheck.kdl");
+static HIPCHECK_TOML: &str = include_str!("../../config/Hipcheck.toml");
+static LANGS_TOML: &str = include_str!("../../config/Langs.toml");
+static LOCAL_HIPCHECK_KDL: &str = include_str!("../../config/local.Hipcheck.kdl");
```
Comment (mchernicoff) [inline hipcheck/src/setup.rs:12]: Do we want a `local.Hipcheck.kdl` file in everyone's version of Hipcheck, or is that just a developer tool we are using?

Comment (j-lanson) [reply hipcheck/src/setup.rs:12]: Good point, we should not have `local.Hipcheck.kdl` included

Comment (KirilldogU) [reply hipcheck/src/setup.rs]: Thanks for input, it's removed!

**Review by j-lanson — APPROVED** [review]
