### PR TITLE
fix: allow analysis-only policies

### LINKED ISSUE #1000: Fix running Hipcheck with analysis not inside of a `category` block
Right now, if you try running the default policy file modified to not have any `category` blocks, with `analysis` entries directly under the `analyses` block, you get strange configuration failures. This seems to be because of our `PolicyFile` parsing code implicitly requiring at least one `category` block, causing the entries to be missing from the resulting structure.

This file causes it with the latest from `main` and with other policy files under a `policy/` directory:

```
plugins {
    plugin "mitre/activity" version="^0.4" manifest="https://hipcheck.mitre.org/dl/plugin/mitre/activity.kdl"
    plugin "mitre/affiliation" version="^0.4" manifest="https://hipcheck.mitre.org/dl/plugin/mitre/affiliation.kdl"
    plugin "mitre/binary" version="^0.3" manifest="https://hipcheck.mitre.org/dl/plugin/mitre/binary.kdl"
    plugin "mitre/churn" version="^0.4" manifest="https://hipcheck.mitre.org/dl/plugin/mitre/churn.kdl"
    plugin "mitre/entropy" version="^0.4" manifest="https://hipcheck.mitre.org/dl/plugin/mitre/entropy.kdl"
    plugin "mitre/fuzz" version="^0.2" manifest="https://hipcheck.mitre.org/dl/plugin/mitre/fuzz.kdl"
    plugin "mitre/review" version="^0.3" manifest="https://hipcheck.mitre.org/dl/plugin/mitre/review.kdl"
    plugin "mitre/typo" version="^0.3" manifest="https://hipcheck.mitre.org/dl/plugin/mitre/typo.kdl"
}

patch {
    plugin "mitre/github" {
        api-token-var "HC_GITHUB_TOKEN"
    }

    plugin "mitre/linguist" {
        langs-file #rel("policy/Langs.kdl")
    }
}

analyze {
    investigate policy="(gt 0.5 $)"
    investigate-if-fail "mitre/typo" "mitre/binary"

    // When was the project last updated?
    analysis "mitre/activity" {
        weeks 52
    }

    // Does the project do fuzz testing?
    analysis "mitre/fuzz"

    // How often pull requests receive an approving review prior to merging?
    analysis "mitre/review" {
        percent-threshold 0.15
    }

    // Does the source repository have binary files checked into it.
    analysis "mitre/binary" {
        binary-file #rel("policy/Binary.kdl")
        binary-file-threshold 0
    }

    // Do any dependencies appear to be typos of popular package names?
    analysis "mitre/typo" {
        typo-file #rel("policy/Typos.kdl")
        count-threshold 0
    }

    // Are there many unusually-large commits in the source repo history?
    analysis "mitre/churn"

    // Are there any textually-unusual commits in the source repo history?
    analysis "mitre/entropy"

    // Are there contributors affiliated with an organization of concern?
    analysis "mitre/affiliation" {
        orgs-file #rel("policy/Orgs.kdl")
        count-threshold 0
    }
}
```

### PR DESCRIPTION
**Pull request by aamohd**
Closes #1000 

Tested with this `local.Hipcheck.kdl` policy file and all related files within `./config`

```
plugins {
    plugin "mitre/activity" version="0.0.0" manifest="plugins/activity/local-plugin.kdl"
    plugin "mitre/affiliation" version="0.0.0" manifest="plugins/affiliation/local-plugin.kdl"
    plugin "mitre/binary" version="0.0.0" manifest="plugins/binary/local-plugin.kdl"
    plugin "mitre/churn" version="0.0.0" manifest="plugins/churn/local-plugin.kdl"
    plugin "mitre/entropy" version="0.0.0" manifest="plugins/entropy/local-plugin.kdl"
    plugin "mitre/fuzz" version="0.0.0" manifest="plugins/fuzz/local-plugin.kdl"
    plugin "mitre/review" version="0.0.0" manifest="plugins/review/local-plugin.kdl"
    plugin "mitre/typo" version="0.0.0" manifest="plugins/typo/local-plugin.kdl"
}

patch {
    plugin "mitre/github" {
        api-token-var "HC_GITHUB_TOKEN"
    }

    plugin "mitre/linguist" {
        langs-file #rel("Langs.kdl")
    }
}

analyze {
    investigate policy="(gt 0.5 $)"
    investigate-if-fail "mitre/typo" "mitre/binary"


    analysis "mitre/activity" policy="(lte $ P52w)" weight=3
    analysis "mitre/binary" {
        binary-file #rel("Binary.kdl")
        binary-file-threshold 0
    }
    analysis "mitre/fuzz" policy="(eq #t $)"
    analysis "mitre/review" policy="(lte (divz (count (filter (eq #f) $)) (count $)) 0.05)"


    analysis "mitre/typo" {
        typo-file #rel("Typos.kdl")
        count-threshold 0
    }

    analysis "mitre/affiliation" {
        orgs-file #rel("Orgs.kdl")
        count-threshold 0
    }

    analysis "mitre/entropy" policy="(eq 0 (count (filter (gt 8.0) $)))" {
        entropy-threshold 10.0
        commit-percentage 0.0
    }
    analysis "mitre/churn" policy="(lte (divz (count (filter (gt 3) $)) (count $)) 0.02)"

}
```

### CODE REVIEW

File: hipcheck/src/policy/policy_file.rs [hunk 1]
```diff
@@ -480,6 +480,7 @@ pub struct PolicyAnalyze {
 	pub investigate_policy: InvestigatePolicy,
 	pub if_fail: Option<InvestigateIfFail>,
 	pub categories: Vec<PolicyCategory>,
+	pub analyses: Vec<PolicyAnalysis>,
```
Comment (j-lanson) [inline hipcheck/src/policy/policy_file.rs:483]: I know I said differently previously, but I would combine these into a single `pub analyses: PolicyCategory`, with the root category called `risk`, same as how it done in `pub fn unresolved_analysis_tree_from_policy()`.

File: hipcheck/src/policy/policy_file.rs [hunk 2]
```diff
@@ -516,9 +519,20 @@ impl PolicyAnalyze {
...
+		}
+
+		self.analyses.iter().find(|p| {
+			let analysis_name = format!(
+				"{}/{}",
+				p.name.publisher.0.as_str(),
+				p.name.name.0.as_str()
+			);
+			analysis_name == name
+		}).cloned()
```
Comment (j-lanson) [inline hipcheck/src/policy/policy_file.rs:535]: By making the above requested change, we can eliminate this messiness and just do `self.analyses.find_analysis_by_name(name)`

**Review by j-lanson — CHANGES_REQUESTED** [review]

File: hipcheck/src/policy/policy_file.rs [hunk 3]
```diff
@@ -538,13 +541,26 @@ impl ParseKdlNode for PolicyAnalyze {
...
+					free_analyses.push(PolicyCategoryChild::Analysis(analysis.clone()));
+				}
+			}
+		}
+
+		if !free_analyses.is_empty() {
+			let mut risk = PolicyCategory::new("risk".to_string(), None);
+			risk.children = free_analyses;
+			categories.push(risk);
+
```
Comment (j-lanson) [inline hipcheck/src/policy/policy_file.rs:563]: Sorry about the confusion. I want a single base category called "risk" under which all categories and free analyses exist. 
So there would be no more `self.categories` field, just a single `self.root: PolicyCategory`.

**Review by j-lanson — CHANGES_REQUESTED** [review]
